/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiterRouteImport } from './routes/witer'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PautaRouteImport } from './routes/pauta'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as NuestraHistoriaRouteImport } from './routes/nuestra-historia'
import { Route as MarcaRouteImport } from './routes/marca'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminLabRouteImport } from './routes/admin-lab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWitVideoIdeaRouteImport } from './routes/api/wit-video-idea'
import { Route as ApiVideoRequestsRouteImport } from './routes/api/video-requests'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiUploadVideoRawRouteImport } from './routes/api/upload-video-raw'
import { Route as ApiUploadReferenceRouteImport } from './routes/api/upload-reference'
import { Route as ApiSubmitSatisfactionRouteImport } from './routes/api/submit-satisfaction'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiRequestRevisionRouteImport } from './routes/api/request-revision'
import { Route as ApiRequestChangeRouteImport } from './routes/api/request-change'
import { Route as ApiPurchasePackRouteImport } from './routes/api/purchase-pack'
import { Route as ApiMetaLocationSearchRouteImport } from './routes/api/meta-location-search'
import { Route as ApiMetaInterestSuggestionsRouteImport } from './routes/api/meta-interest-suggestions'
import { Route as ApiMetaInterestSearchRouteImport } from './routes/api/meta-interest-search'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as ApiGeoPriceRouteImport } from './routes/api/geo-price'
import { Route as ApiGenerateAdCopyRouteImport } from './routes/api/generate-ad-copy'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiCloseRequestRouteImport } from './routes/api/close-request'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiCarouselRequestsRouteImport } from './routes/api/carousel-requests'
import { Route as ApiCarouselRequestChangeRouteImport } from './routes/api/carousel-request-change'
import { Route as ApiCampaignsCreateRouteImport } from './routes/api/campaigns-create'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiBrandProfileManualRouteImport } from './routes/api/brand-profile-manual'
import { Route as ApiBrandProfileColorsRouteImport } from './routes/api/brand-profile-colors'
import { Route as ApiBrandProfileRouteImport } from './routes/api/brand-profile'
import { Route as ApiWitChatRouteImport } from './routes/api/wit/chat'
import { Route as ApiWitCarouselChatRouteImport } from './routes/api/wit/carousel-chat'
import { Route as ApiStripeCreatePaymentIntentRouteImport } from './routes/api/stripe/create-payment-intent'
import { Route as ApiPublicShowcaseImageRouteImport } from './routes/api/public/showcase-image'
import { Route as ApiPublicShowcaseRouteImport } from './routes/api/public/showcase'
import { Route as ApiPublicReviewsRouteImport } from './routes/api/public/reviews'
import { Route as ApiPublicBrandsRouteImport } from './routes/api/public/brands'
import { Route as ApiPublicBrandLogoRouteImport } from './routes/api/public/brand-logo'
import { Route as ApiOnboardingDraftRouteImport } from './routes/api/onboarding/draft'
import { Route as ApiOnboardingCompleteRouteImport } from './routes/api/onboarding/complete'
import { Route as ApiDesignerVideoRequestsRouteImport } from './routes/api/designer/video-requests'
import { Route as ApiDesignerRequestsRouteImport } from './routes/api/designer/requests'
import { Route as ApiDesignerClaimVideoRouteImport } from './routes/api/designer/claim-video'
import { Route as ApiDesignerClaimCarouselRouteImport } from './routes/api/designer/claim-carousel'
import { Route as ApiDesignerClaimRouteImport } from './routes/api/designer/claim'
import { Route as ApiDesignerCarouselRequestsRouteImport } from './routes/api/designer/carousel-requests'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminVerifyPinRouteImport } from './routes/api/admin/verify-pin'
import { Route as ApiAdminUpdateRequestRouteImport } from './routes/api/admin/update-request'
import { Route as ApiAdminUpdateDiscountCodeRouteImport } from './routes/api/admin/update-discount-code'
import { Route as ApiAdminUpdateDesignerRouteImport } from './routes/api/admin/update-designer'
import { Route as ApiAdminUpdateBrandProfileRouteImport } from './routes/api/admin/update-brand-profile'
import { Route as ApiAdminToggleLogoVisibilityRouteImport } from './routes/api/admin/toggle-logo-visibility'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminGrantRequestsRouteImport } from './routes/api/admin/grant-requests'
import { Route as ApiAdminDiscardResultRouteImport } from './routes/api/admin/discard-result'
import { Route as ApiAdminDeliverVideoRouteImport } from './routes/api/admin/deliver-video'
import { Route as ApiAdminDeliverCarouselSlideRouteImport } from './routes/api/admin/deliver-carousel-slide'
import { Route as ApiAdminDeliverRouteImport } from './routes/api/admin/deliver'
import { Route as ApiAdminDeleteRequestRouteImport } from './routes/api/admin/delete-request'
import { Route as ApiAdminDeleteDiscountCodeRouteImport } from './routes/api/admin/delete-discount-code'
import { Route as ApiAdminDeactivateDiscountCodeRouteImport } from './routes/api/admin/deactivate-discount-code'
import { Route as ApiAdminDeactivateDesignerRouteImport } from './routes/api/admin/deactivate-designer'
import { Route as ApiAdminCreateDiscountCodeRouteImport } from './routes/api/admin/create-discount-code'
import { Route as ApiAdminCreateDesignerRouteImport } from './routes/api/admin/create-designer'
import { Route as ApiAdminApproveResultRouteImport } from './routes/api/admin/approve-result'
import { Route as ApiAdminAiFillRouteImport } from './routes/api/admin/ai-fill'
import { Route as ApiAdminActivateMembershipRouteImport } from './routes/api/admin/activate-membership'
import { Route as ApiAdminActivateChangeRouteImport } from './routes/api/admin/activate-change'
import { Route as ApiAccountUpdateNameRouteImport } from './routes/api/account/update-name'
import { Route as ApiAccountChangePasswordRouteImport } from './routes/api/account/change-password'

const WiterRoute = WiterRouteImport.update({
  id: '/witer',
  path: '/witer',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PautaRoute = PautaRouteImport.update({
  id: '/pauta',
  path: '/pauta',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const NuestraHistoriaRoute = NuestraHistoriaRouteImport.update({
  id: '/nuestra-historia',
  path: '/nuestra-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaRoute = MarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLabRoute = AdminLabRouteImport.update({
  id: '/admin-lab',
  path: '/admin-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWitVideoIdeaRoute = ApiWitVideoIdeaRouteImport.update({
  id: '/api/wit-video-idea',
  path: '/api/wit-video-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRequestsRoute = ApiVideoRequestsRouteImport.update({
  id: '/api/video-requests',
  path: '/api/video-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadVideoRawRoute = ApiUploadVideoRawRouteImport.update({
  id: '/api/upload-video-raw',
  path: '/api/upload-video-raw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadReferenceRoute = ApiUploadReferenceRouteImport.update({
  id: '/api/upload-reference',
  path: '/api/upload-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitSatisfactionRoute = ApiSubmitSatisfactionRouteImport.update({
  id: '/api/submit-satisfaction',
  path: '/api/submit-satisfaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestRevisionRoute = ApiRequestRevisionRouteImport.update({
  id: '/api/request-revision',
  path: '/api/request-revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestChangeRoute = ApiRequestChangeRouteImport.update({
  id: '/api/request-change',
  path: '/api/request-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasePackRoute = ApiPurchasePackRouteImport.update({
  id: '/api/purchase-pack',
  path: '/api/purchase-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaLocationSearchRoute = ApiMetaLocationSearchRouteImport.update({
  id: '/api/meta-location-search',
  path: '/api/meta-location-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaInterestSuggestionsRoute =
  ApiMetaInterestSuggestionsRouteImport.update({
    id: '/api/meta-interest-suggestions',
    path: '/api/meta-interest-suggestions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaInterestSearchRoute = ApiMetaInterestSearchRouteImport.update({
  id: '/api/meta-interest-search',
  path: '/api/meta-interest-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeoPriceRoute = ApiGeoPriceRouteImport.update({
  id: '/api/geo-price',
  path: '/api/geo-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAdCopyRoute = ApiGenerateAdCopyRouteImport.update({
  id: '/api/generate-ad-copy',
  path: '/api/generate-ad-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloseRequestRoute = ApiCloseRequestRouteImport.update({
  id: '/api/close-request',
  path: '/api/close-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarouselRequestsRoute = ApiCarouselRequestsRouteImport.update({
  id: '/api/carousel-requests',
  path: '/api/carousel-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarouselRequestChangeRoute =
  ApiCarouselRequestChangeRouteImport.update({
    id: '/api/carousel-request-change',
    path: '/api/carousel-request-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCampaignsCreateRoute = ApiCampaignsCreateRouteImport.update({
  id: '/api/campaigns-create',
  path: '/api/campaigns-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileManualRoute = ApiBrandProfileManualRouteImport.update({
  id: '/api/brand-profile-manual',
  path: '/api/brand-profile-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileColorsRoute = ApiBrandProfileColorsRouteImport.update({
  id: '/api/brand-profile-colors',
  path: '/api/brand-profile-colors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileRoute = ApiBrandProfileRouteImport.update({
  id: '/api/brand-profile',
  path: '/api/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWitChatRoute = ApiWitChatRouteImport.update({
  id: '/api/wit/chat',
  path: '/api/wit/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWitCarouselChatRoute = ApiWitCarouselChatRouteImport.update({
  id: '/api/wit/carousel-chat',
  path: '/api/wit/carousel-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeCreatePaymentIntentRoute =
  ApiStripeCreatePaymentIntentRouteImport.update({
    id: '/api/stripe/create-payment-intent',
    path: '/api/stripe/create-payment-intent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShowcaseImageRoute = ApiPublicShowcaseImageRouteImport.update({
  id: '/api/public/showcase-image',
  path: '/api/public/showcase-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShowcaseRoute = ApiPublicShowcaseRouteImport.update({
  id: '/api/public/showcase',
  path: '/api/public/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewsRoute = ApiPublicReviewsRouteImport.update({
  id: '/api/public/reviews',
  path: '/api/public/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandsRoute = ApiPublicBrandsRouteImport.update({
  id: '/api/public/brands',
  path: '/api/public/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandLogoRoute = ApiPublicBrandLogoRouteImport.update({
  id: '/api/public/brand-logo',
  path: '/api/public/brand-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingDraftRoute = ApiOnboardingDraftRouteImport.update({
  id: '/api/onboarding/draft',
  path: '/api/onboarding/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCompleteRoute = ApiOnboardingCompleteRouteImport.update({
  id: '/api/onboarding/complete',
  path: '/api/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerVideoRequestsRoute =
  ApiDesignerVideoRequestsRouteImport.update({
    id: '/api/designer/video-requests',
    path: '/api/designer/video-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDesignerRequestsRoute = ApiDesignerRequestsRouteImport.update({
  id: '/api/designer/requests',
  path: '/api/designer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerClaimVideoRoute = ApiDesignerClaimVideoRouteImport.update({
  id: '/api/designer/claim-video',
  path: '/api/designer/claim-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerClaimCarouselRoute =
  ApiDesignerClaimCarouselRouteImport.update({
    id: '/api/designer/claim-carousel',
    path: '/api/designer/claim-carousel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDesignerClaimRoute = ApiDesignerClaimRouteImport.update({
  id: '/api/designer/claim',
  path: '/api/designer/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerCarouselRequestsRoute =
  ApiDesignerCarouselRequestsRouteImport.update({
    id: '/api/designer/carousel-requests',
    path: '/api/designer/carousel-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyPinRoute = ApiAdminVerifyPinRouteImport.update({
  id: '/api/admin/verify-pin',
  path: '/api/admin/verify-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateRequestRoute = ApiAdminUpdateRequestRouteImport.update({
  id: '/api/admin/update-request',
  path: '/api/admin/update-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateDiscountCodeRoute =
  ApiAdminUpdateDiscountCodeRouteImport.update({
    id: '/api/admin/update-discount-code',
    path: '/api/admin/update-discount-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUpdateDesignerRoute = ApiAdminUpdateDesignerRouteImport.update({
  id: '/api/admin/update-designer',
  path: '/api/admin/update-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateBrandProfileRoute =
  ApiAdminUpdateBrandProfileRouteImport.update({
    id: '/api/admin/update-brand-profile',
    path: '/api/admin/update-brand-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminToggleLogoVisibilityRoute =
  ApiAdminToggleLogoVisibilityRouteImport.update({
    id: '/api/admin/toggle-logo-visibility',
    path: '/api/admin/toggle-logo-visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGrantRequestsRoute = ApiAdminGrantRequestsRouteImport.update({
  id: '/api/admin/grant-requests',
  path: '/api/admin/grant-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDiscardResultRoute = ApiAdminDiscardResultRouteImport.update({
  id: '/api/admin/discard-result',
  path: '/api/admin/discard-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliverVideoRoute = ApiAdminDeliverVideoRouteImport.update({
  id: '/api/admin/deliver-video',
  path: '/api/admin/deliver-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliverCarouselSlideRoute =
  ApiAdminDeliverCarouselSlideRouteImport.update({
    id: '/api/admin/deliver-carousel-slide',
    path: '/api/admin/deliver-carousel-slide',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDeliverRoute = ApiAdminDeliverRouteImport.update({
  id: '/api/admin/deliver',
  path: '/api/admin/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteRequestRoute = ApiAdminDeleteRequestRouteImport.update({
  id: '/api/admin/delete-request',
  path: '/api/admin/delete-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteDiscountCodeRoute =
  ApiAdminDeleteDiscountCodeRouteImport.update({
    id: '/api/admin/delete-discount-code',
    path: '/api/admin/delete-discount-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDeactivateDiscountCodeRoute =
  ApiAdminDeactivateDiscountCodeRouteImport.update({
    id: '/api/admin/deactivate-discount-code',
    path: '/api/admin/deactivate-discount-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDeactivateDesignerRoute =
  ApiAdminDeactivateDesignerRouteImport.update({
    id: '/api/admin/deactivate-designer',
    path: '/api/admin/deactivate-designer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCreateDiscountCodeRoute =
  ApiAdminCreateDiscountCodeRouteImport.update({
    id: '/api/admin/create-discount-code',
    path: '/api/admin/create-discount-code',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCreateDesignerRoute = ApiAdminCreateDesignerRouteImport.update({
  id: '/api/admin/create-designer',
  path: '/api/admin/create-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveResultRoute = ApiAdminApproveResultRouteImport.update({
  id: '/api/admin/approve-result',
  path: '/api/admin/approve-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiFillRoute = ApiAdminAiFillRouteImport.update({
  id: '/api/admin/ai-fill',
  path: '/api/admin/ai-fill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivateMembershipRoute =
  ApiAdminActivateMembershipRouteImport.update({
    id: '/api/admin/activate-membership',
    path: '/api/admin/activate-membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminActivateChangeRoute = ApiAdminActivateChangeRouteImport.update({
  id: '/api/admin/activate-change',
  path: '/api/admin/activate-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountUpdateNameRoute = ApiAccountUpdateNameRouteImport.update({
  id: '/api/account/update-name',
  path: '/api/account/update-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountChangePasswordRoute =
  ApiAccountChangePasswordRouteImport.update({
    id: '/api/account/change-password',
    path: '/api/account/change-password',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/marca': typeof MarcaRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/pauta': typeof PautaRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/upgrade': typeof UpgradeRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/brand-profile-colors': typeof ApiBrandProfileColorsRoute
  '/api/brand-profile-manual': typeof ApiBrandProfileManualRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/campaigns-create': typeof ApiCampaignsCreateRoute
  '/api/carousel-request-change': typeof ApiCarouselRequestChangeRoute
  '/api/carousel-requests': typeof ApiCarouselRequestsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/geo-price': typeof ApiGeoPriceRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/meta-interest-search': typeof ApiMetaInterestSearchRoute
  '/api/meta-interest-suggestions': typeof ApiMetaInterestSuggestionsRoute
  '/api/meta-location-search': typeof ApiMetaLocationSearchRoute
  '/api/purchase-pack': typeof ApiPurchasePackRoute
  '/api/request-change': typeof ApiRequestChangeRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/upload-video-raw': typeof ApiUploadVideoRawRoute
  '/api/user': typeof ApiUserRoute
  '/api/video-requests': typeof ApiVideoRequestsRoute
  '/api/wit-video-idea': typeof ApiWitVideoIdeaRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/update-name': typeof ApiAccountUpdateNameRoute
  '/api/admin/activate-change': typeof ApiAdminActivateChangeRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/create-discount-code': typeof ApiAdminCreateDiscountCodeRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/deactivate-discount-code': typeof ApiAdminDeactivateDiscountCodeRoute
  '/api/admin/delete-discount-code': typeof ApiAdminDeleteDiscountCodeRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/deliver-carousel-slide': typeof ApiAdminDeliverCarouselSlideRoute
  '/api/admin/deliver-video': typeof ApiAdminDeliverVideoRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/grant-requests': typeof ApiAdminGrantRequestsRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-discount-code': typeof ApiAdminUpdateDiscountCodeRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/admin/verify-pin': typeof ApiAdminVerifyPinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/carousel-requests': typeof ApiDesignerCarouselRequestsRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/claim-carousel': typeof ApiDesignerClaimCarouselRoute
  '/api/designer/claim-video': typeof ApiDesignerClaimVideoRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/designer/video-requests': typeof ApiDesignerVideoRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/stripe/create-payment-intent': typeof ApiStripeCreatePaymentIntentRoute
  '/api/wit/carousel-chat': typeof ApiWitCarouselChatRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/marca': typeof MarcaRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/pauta': typeof PautaRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/upgrade': typeof UpgradeRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/brand-profile-colors': typeof ApiBrandProfileColorsRoute
  '/api/brand-profile-manual': typeof ApiBrandProfileManualRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/campaigns-create': typeof ApiCampaignsCreateRoute
  '/api/carousel-request-change': typeof ApiCarouselRequestChangeRoute
  '/api/carousel-requests': typeof ApiCarouselRequestsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/geo-price': typeof ApiGeoPriceRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/meta-interest-search': typeof ApiMetaInterestSearchRoute
  '/api/meta-interest-suggestions': typeof ApiMetaInterestSuggestionsRoute
  '/api/meta-location-search': typeof ApiMetaLocationSearchRoute
  '/api/purchase-pack': typeof ApiPurchasePackRoute
  '/api/request-change': typeof ApiRequestChangeRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/upload-video-raw': typeof ApiUploadVideoRawRoute
  '/api/user': typeof ApiUserRoute
  '/api/video-requests': typeof ApiVideoRequestsRoute
  '/api/wit-video-idea': typeof ApiWitVideoIdeaRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/update-name': typeof ApiAccountUpdateNameRoute
  '/api/admin/activate-change': typeof ApiAdminActivateChangeRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/create-discount-code': typeof ApiAdminCreateDiscountCodeRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/deactivate-discount-code': typeof ApiAdminDeactivateDiscountCodeRoute
  '/api/admin/delete-discount-code': typeof ApiAdminDeleteDiscountCodeRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/deliver-carousel-slide': typeof ApiAdminDeliverCarouselSlideRoute
  '/api/admin/deliver-video': typeof ApiAdminDeliverVideoRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/grant-requests': typeof ApiAdminGrantRequestsRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-discount-code': typeof ApiAdminUpdateDiscountCodeRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/admin/verify-pin': typeof ApiAdminVerifyPinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/carousel-requests': typeof ApiDesignerCarouselRequestsRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/claim-carousel': typeof ApiDesignerClaimCarouselRoute
  '/api/designer/claim-video': typeof ApiDesignerClaimVideoRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/designer/video-requests': typeof ApiDesignerVideoRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/stripe/create-payment-intent': typeof ApiStripeCreatePaymentIntentRoute
  '/api/wit/carousel-chat': typeof ApiWitCarouselChatRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/marca': typeof MarcaRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/pauta': typeof PautaRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/upgrade': typeof UpgradeRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/brand-profile-colors': typeof ApiBrandProfileColorsRoute
  '/api/brand-profile-manual': typeof ApiBrandProfileManualRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/campaigns-create': typeof ApiCampaignsCreateRoute
  '/api/carousel-request-change': typeof ApiCarouselRequestChangeRoute
  '/api/carousel-requests': typeof ApiCarouselRequestsRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/generate-ad-copy': typeof ApiGenerateAdCopyRoute
  '/api/geo-price': typeof ApiGeoPriceRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/meta-interest-search': typeof ApiMetaInterestSearchRoute
  '/api/meta-interest-suggestions': typeof ApiMetaInterestSuggestionsRoute
  '/api/meta-location-search': typeof ApiMetaLocationSearchRoute
  '/api/purchase-pack': typeof ApiPurchasePackRoute
  '/api/request-change': typeof ApiRequestChangeRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/upload-video-raw': typeof ApiUploadVideoRawRoute
  '/api/user': typeof ApiUserRoute
  '/api/video-requests': typeof ApiVideoRequestsRoute
  '/api/wit-video-idea': typeof ApiWitVideoIdeaRoute
  '/api/account/change-password': typeof ApiAccountChangePasswordRoute
  '/api/account/update-name': typeof ApiAccountUpdateNameRoute
  '/api/admin/activate-change': typeof ApiAdminActivateChangeRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/create-discount-code': typeof ApiAdminCreateDiscountCodeRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/deactivate-discount-code': typeof ApiAdminDeactivateDiscountCodeRoute
  '/api/admin/delete-discount-code': typeof ApiAdminDeleteDiscountCodeRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/deliver-carousel-slide': typeof ApiAdminDeliverCarouselSlideRoute
  '/api/admin/deliver-video': typeof ApiAdminDeliverVideoRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/grant-requests': typeof ApiAdminGrantRequestsRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-discount-code': typeof ApiAdminUpdateDiscountCodeRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/admin/verify-pin': typeof ApiAdminVerifyPinRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/carousel-requests': typeof ApiDesignerCarouselRequestsRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/claim-carousel': typeof ApiDesignerClaimCarouselRoute
  '/api/designer/claim-video': typeof ApiDesignerClaimVideoRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/designer/video-requests': typeof ApiDesignerVideoRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/stripe/create-payment-intent': typeof ApiStripeCreatePaymentIntentRoute
  '/api/wit/carousel-chat': typeof ApiWitCarouselChatRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/marca'
    | '/nuestra-historia'
    | '/panel'
    | '/pauta'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terminos'
    | '/upgrade'
    | '/witer'
    | '/api/brand-profile'
    | '/api/brand-profile-colors'
    | '/api/brand-profile-manual'
    | '/api/campaigns'
    | '/api/campaigns-create'
    | '/api/carousel-request-change'
    | '/api/carousel-requests'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/generate-ad-copy'
    | '/api/geo-price'
    | '/api/geocode'
    | '/api/meta-interest-search'
    | '/api/meta-interest-suggestions'
    | '/api/meta-location-search'
    | '/api/purchase-pack'
    | '/api/request-change'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/upload-video-raw'
    | '/api/user'
    | '/api/video-requests'
    | '/api/wit-video-idea'
    | '/api/account/change-password'
    | '/api/account/update-name'
    | '/api/admin/activate-change'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/create-discount-code'
    | '/api/admin/deactivate-designer'
    | '/api/admin/deactivate-discount-code'
    | '/api/admin/delete-discount-code'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/deliver-carousel-slide'
    | '/api/admin/deliver-video'
    | '/api/admin/discard-result'
    | '/api/admin/grant-requests'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-discount-code'
    | '/api/admin/update-request'
    | '/api/admin/verify-pin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/carousel-requests'
    | '/api/designer/claim'
    | '/api/designer/claim-carousel'
    | '/api/designer/claim-video'
    | '/api/designer/requests'
    | '/api/designer/video-requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/stripe/create-payment-intent'
    | '/api/wit/carousel-chat'
    | '/api/wit/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/marca'
    | '/nuestra-historia'
    | '/panel'
    | '/pauta'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terminos'
    | '/upgrade'
    | '/witer'
    | '/api/brand-profile'
    | '/api/brand-profile-colors'
    | '/api/brand-profile-manual'
    | '/api/campaigns'
    | '/api/campaigns-create'
    | '/api/carousel-request-change'
    | '/api/carousel-requests'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/generate-ad-copy'
    | '/api/geo-price'
    | '/api/geocode'
    | '/api/meta-interest-search'
    | '/api/meta-interest-suggestions'
    | '/api/meta-location-search'
    | '/api/purchase-pack'
    | '/api/request-change'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/upload-video-raw'
    | '/api/user'
    | '/api/video-requests'
    | '/api/wit-video-idea'
    | '/api/account/change-password'
    | '/api/account/update-name'
    | '/api/admin/activate-change'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/create-discount-code'
    | '/api/admin/deactivate-designer'
    | '/api/admin/deactivate-discount-code'
    | '/api/admin/delete-discount-code'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/deliver-carousel-slide'
    | '/api/admin/deliver-video'
    | '/api/admin/discard-result'
    | '/api/admin/grant-requests'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-discount-code'
    | '/api/admin/update-request'
    | '/api/admin/verify-pin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/carousel-requests'
    | '/api/designer/claim'
    | '/api/designer/claim-carousel'
    | '/api/designer/claim-video'
    | '/api/designer/requests'
    | '/api/designer/video-requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/stripe/create-payment-intent'
    | '/api/wit/carousel-chat'
    | '/api/wit/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/marca'
    | '/nuestra-historia'
    | '/panel'
    | '/pauta'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terminos'
    | '/upgrade'
    | '/witer'
    | '/api/brand-profile'
    | '/api/brand-profile-colors'
    | '/api/brand-profile-manual'
    | '/api/campaigns'
    | '/api/campaigns-create'
    | '/api/carousel-request-change'
    | '/api/carousel-requests'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/generate-ad-copy'
    | '/api/geo-price'
    | '/api/geocode'
    | '/api/meta-interest-search'
    | '/api/meta-interest-suggestions'
    | '/api/meta-location-search'
    | '/api/purchase-pack'
    | '/api/request-change'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/upload-video-raw'
    | '/api/user'
    | '/api/video-requests'
    | '/api/wit-video-idea'
    | '/api/account/change-password'
    | '/api/account/update-name'
    | '/api/admin/activate-change'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/create-discount-code'
    | '/api/admin/deactivate-designer'
    | '/api/admin/deactivate-discount-code'
    | '/api/admin/delete-discount-code'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/deliver-carousel-slide'
    | '/api/admin/deliver-video'
    | '/api/admin/discard-result'
    | '/api/admin/grant-requests'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-discount-code'
    | '/api/admin/update-request'
    | '/api/admin/verify-pin'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/carousel-requests'
    | '/api/designer/claim'
    | '/api/designer/claim-carousel'
    | '/api/designer/claim-video'
    | '/api/designer/requests'
    | '/api/designer/video-requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/stripe/create-payment-intent'
    | '/api/wit/carousel-chat'
    | '/api/wit/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLabRoute: typeof AdminLabRoute
  CheckoutRoute: typeof CheckoutRoute
  IngresarRoute: typeof IngresarRoute
  MarcaRoute: typeof MarcaRoute
  NuestraHistoriaRoute: typeof NuestraHistoriaRoute
  PanelRoute: typeof PanelRoute
  PautaRoute: typeof PautaRoute
  RegistroRoute: typeof RegistroRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  UpgradeRoute: typeof UpgradeRoute
  WiterRoute: typeof WiterRoute
  ApiBrandProfileRoute: typeof ApiBrandProfileRoute
  ApiBrandProfileColorsRoute: typeof ApiBrandProfileColorsRoute
  ApiBrandProfileManualRoute: typeof ApiBrandProfileManualRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiCampaignsCreateRoute: typeof ApiCampaignsCreateRoute
  ApiCarouselRequestChangeRoute: typeof ApiCarouselRequestChangeRoute
  ApiCarouselRequestsRoute: typeof ApiCarouselRequestsRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCloseRequestRoute: typeof ApiCloseRequestRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiGenerateAdCopyRoute: typeof ApiGenerateAdCopyRoute
  ApiGeoPriceRoute: typeof ApiGeoPriceRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiMetaInterestSearchRoute: typeof ApiMetaInterestSearchRoute
  ApiMetaInterestSuggestionsRoute: typeof ApiMetaInterestSuggestionsRoute
  ApiMetaLocationSearchRoute: typeof ApiMetaLocationSearchRoute
  ApiPurchasePackRoute: typeof ApiPurchasePackRoute
  ApiRequestChangeRoute: typeof ApiRequestChangeRoute
  ApiRequestRevisionRoute: typeof ApiRequestRevisionRoute
  ApiRequestsRoute: typeof ApiRequestsRoute
  ApiSubmitSatisfactionRoute: typeof ApiSubmitSatisfactionRoute
  ApiUploadReferenceRoute: typeof ApiUploadReferenceRoute
  ApiUploadVideoRawRoute: typeof ApiUploadVideoRawRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiVideoRequestsRoute: typeof ApiVideoRequestsRoute
  ApiWitVideoIdeaRoute: typeof ApiWitVideoIdeaRoute
  ApiAccountChangePasswordRoute: typeof ApiAccountChangePasswordRoute
  ApiAccountUpdateNameRoute: typeof ApiAccountUpdateNameRoute
  ApiAdminActivateChangeRoute: typeof ApiAdminActivateChangeRoute
  ApiAdminActivateMembershipRoute: typeof ApiAdminActivateMembershipRoute
  ApiAdminAiFillRoute: typeof ApiAdminAiFillRoute
  ApiAdminApproveResultRoute: typeof ApiAdminApproveResultRoute
  ApiAdminCreateDesignerRoute: typeof ApiAdminCreateDesignerRoute
  ApiAdminCreateDiscountCodeRoute: typeof ApiAdminCreateDiscountCodeRoute
  ApiAdminDeactivateDesignerRoute: typeof ApiAdminDeactivateDesignerRoute
  ApiAdminDeactivateDiscountCodeRoute: typeof ApiAdminDeactivateDiscountCodeRoute
  ApiAdminDeleteDiscountCodeRoute: typeof ApiAdminDeleteDiscountCodeRoute
  ApiAdminDeleteRequestRoute: typeof ApiAdminDeleteRequestRoute
  ApiAdminDeliverRoute: typeof ApiAdminDeliverRoute
  ApiAdminDeliverCarouselSlideRoute: typeof ApiAdminDeliverCarouselSlideRoute
  ApiAdminDeliverVideoRoute: typeof ApiAdminDeliverVideoRoute
  ApiAdminDiscardResultRoute: typeof ApiAdminDiscardResultRoute
  ApiAdminGrantRequestsRoute: typeof ApiAdminGrantRequestsRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminToggleLogoVisibilityRoute: typeof ApiAdminToggleLogoVisibilityRoute
  ApiAdminUpdateBrandProfileRoute: typeof ApiAdminUpdateBrandProfileRoute
  ApiAdminUpdateDesignerRoute: typeof ApiAdminUpdateDesignerRoute
  ApiAdminUpdateDiscountCodeRoute: typeof ApiAdminUpdateDiscountCodeRoute
  ApiAdminUpdateRequestRoute: typeof ApiAdminUpdateRequestRoute
  ApiAdminVerifyPinRoute: typeof ApiAdminVerifyPinRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDesignerCarouselRequestsRoute: typeof ApiDesignerCarouselRequestsRoute
  ApiDesignerClaimRoute: typeof ApiDesignerClaimRoute
  ApiDesignerClaimCarouselRoute: typeof ApiDesignerClaimCarouselRoute
  ApiDesignerClaimVideoRoute: typeof ApiDesignerClaimVideoRoute
  ApiDesignerRequestsRoute: typeof ApiDesignerRequestsRoute
  ApiDesignerVideoRequestsRoute: typeof ApiDesignerVideoRequestsRoute
  ApiOnboardingCompleteRoute: typeof ApiOnboardingCompleteRoute
  ApiOnboardingDraftRoute: typeof ApiOnboardingDraftRoute
  ApiPublicBrandLogoRoute: typeof ApiPublicBrandLogoRoute
  ApiPublicBrandsRoute: typeof ApiPublicBrandsRoute
  ApiPublicReviewsRoute: typeof ApiPublicReviewsRoute
  ApiPublicShowcaseRoute: typeof ApiPublicShowcaseRoute
  ApiPublicShowcaseImageRoute: typeof ApiPublicShowcaseImageRoute
  ApiStripeCreatePaymentIntentRoute: typeof ApiStripeCreatePaymentIntentRoute
  ApiWitCarouselChatRoute: typeof ApiWitCarouselChatRoute
  ApiWitChatRoute: typeof ApiWitChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/witer': {
      id: '/witer'
      path: '/witer'
      fullPath: '/witer'
      preLoaderRoute: typeof WiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pauta': {
      id: '/pauta'
      path: '/pauta'
      fullPath: '/pauta'
      preLoaderRoute: typeof PautaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuestra-historia': {
      id: '/nuestra-historia'
      path: '/nuestra-historia'
      fullPath: '/nuestra-historia'
      preLoaderRoute: typeof NuestraHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca': {
      id: '/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof MarcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lab': {
      id: '/admin-lab'
      path: '/admin-lab'
      fullPath: '/admin-lab'
      preLoaderRoute: typeof AdminLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wit-video-idea': {
      id: '/api/wit-video-idea'
      path: '/api/wit-video-idea'
      fullPath: '/api/wit-video-idea'
      preLoaderRoute: typeof ApiWitVideoIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-requests': {
      id: '/api/video-requests'
      path: '/api/video-requests'
      fullPath: '/api/video-requests'
      preLoaderRoute: typeof ApiVideoRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-video-raw': {
      id: '/api/upload-video-raw'
      path: '/api/upload-video-raw'
      fullPath: '/api/upload-video-raw'
      preLoaderRoute: typeof ApiUploadVideoRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-reference': {
      id: '/api/upload-reference'
      path: '/api/upload-reference'
      fullPath: '/api/upload-reference'
      preLoaderRoute: typeof ApiUploadReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-satisfaction': {
      id: '/api/submit-satisfaction'
      path: '/api/submit-satisfaction'
      fullPath: '/api/submit-satisfaction'
      preLoaderRoute: typeof ApiSubmitSatisfactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-revision': {
      id: '/api/request-revision'
      path: '/api/request-revision'
      fullPath: '/api/request-revision'
      preLoaderRoute: typeof ApiRequestRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-change': {
      id: '/api/request-change'
      path: '/api/request-change'
      fullPath: '/api/request-change'
      preLoaderRoute: typeof ApiRequestChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchase-pack': {
      id: '/api/purchase-pack'
      path: '/api/purchase-pack'
      fullPath: '/api/purchase-pack'
      preLoaderRoute: typeof ApiPurchasePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-location-search': {
      id: '/api/meta-location-search'
      path: '/api/meta-location-search'
      fullPath: '/api/meta-location-search'
      preLoaderRoute: typeof ApiMetaLocationSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-interest-suggestions': {
      id: '/api/meta-interest-suggestions'
      path: '/api/meta-interest-suggestions'
      fullPath: '/api/meta-interest-suggestions'
      preLoaderRoute: typeof ApiMetaInterestSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-interest-search': {
      id: '/api/meta-interest-search'
      path: '/api/meta-interest-search'
      fullPath: '/api/meta-interest-search'
      preLoaderRoute: typeof ApiMetaInterestSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geo-price': {
      id: '/api/geo-price'
      path: '/api/geo-price'
      fullPath: '/api/geo-price'
      preLoaderRoute: typeof ApiGeoPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-ad-copy': {
      id: '/api/generate-ad-copy'
      path: '/api/generate-ad-copy'
      fullPath: '/api/generate-ad-copy'
      preLoaderRoute: typeof ApiGenerateAdCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/close-request': {
      id: '/api/close-request'
      path: '/api/close-request'
      fullPath: '/api/close-request'
      preLoaderRoute: typeof ApiCloseRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carousel-requests': {
      id: '/api/carousel-requests'
      path: '/api/carousel-requests'
      fullPath: '/api/carousel-requests'
      preLoaderRoute: typeof ApiCarouselRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/carousel-request-change': {
      id: '/api/carousel-request-change'
      path: '/api/carousel-request-change'
      fullPath: '/api/carousel-request-change'
      preLoaderRoute: typeof ApiCarouselRequestChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns-create': {
      id: '/api/campaigns-create'
      path: '/api/campaigns-create'
      fullPath: '/api/campaigns-create'
      preLoaderRoute: typeof ApiCampaignsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-profile-manual': {
      id: '/api/brand-profile-manual'
      path: '/api/brand-profile-manual'
      fullPath: '/api/brand-profile-manual'
      preLoaderRoute: typeof ApiBrandProfileManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-profile-colors': {
      id: '/api/brand-profile-colors'
      path: '/api/brand-profile-colors'
      fullPath: '/api/brand-profile-colors'
      preLoaderRoute: typeof ApiBrandProfileColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-profile': {
      id: '/api/brand-profile'
      path: '/api/brand-profile'
      fullPath: '/api/brand-profile'
      preLoaderRoute: typeof ApiBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wit/chat': {
      id: '/api/wit/chat'
      path: '/api/wit/chat'
      fullPath: '/api/wit/chat'
      preLoaderRoute: typeof ApiWitChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wit/carousel-chat': {
      id: '/api/wit/carousel-chat'
      path: '/api/wit/carousel-chat'
      fullPath: '/api/wit/carousel-chat'
      preLoaderRoute: typeof ApiWitCarouselChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/create-payment-intent': {
      id: '/api/stripe/create-payment-intent'
      path: '/api/stripe/create-payment-intent'
      fullPath: '/api/stripe/create-payment-intent'
      preLoaderRoute: typeof ApiStripeCreatePaymentIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/showcase-image': {
      id: '/api/public/showcase-image'
      path: '/api/public/showcase-image'
      fullPath: '/api/public/showcase-image'
      preLoaderRoute: typeof ApiPublicShowcaseImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/showcase': {
      id: '/api/public/showcase'
      path: '/api/public/showcase'
      fullPath: '/api/public/showcase'
      preLoaderRoute: typeof ApiPublicShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reviews': {
      id: '/api/public/reviews'
      path: '/api/public/reviews'
      fullPath: '/api/public/reviews'
      preLoaderRoute: typeof ApiPublicReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brands': {
      id: '/api/public/brands'
      path: '/api/public/brands'
      fullPath: '/api/public/brands'
      preLoaderRoute: typeof ApiPublicBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand-logo': {
      id: '/api/public/brand-logo'
      path: '/api/public/brand-logo'
      fullPath: '/api/public/brand-logo'
      preLoaderRoute: typeof ApiPublicBrandLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/draft': {
      id: '/api/onboarding/draft'
      path: '/api/onboarding/draft'
      fullPath: '/api/onboarding/draft'
      preLoaderRoute: typeof ApiOnboardingDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/complete': {
      id: '/api/onboarding/complete'
      path: '/api/onboarding/complete'
      fullPath: '/api/onboarding/complete'
      preLoaderRoute: typeof ApiOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/video-requests': {
      id: '/api/designer/video-requests'
      path: '/api/designer/video-requests'
      fullPath: '/api/designer/video-requests'
      preLoaderRoute: typeof ApiDesignerVideoRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/requests': {
      id: '/api/designer/requests'
      path: '/api/designer/requests'
      fullPath: '/api/designer/requests'
      preLoaderRoute: typeof ApiDesignerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/claim-video': {
      id: '/api/designer/claim-video'
      path: '/api/designer/claim-video'
      fullPath: '/api/designer/claim-video'
      preLoaderRoute: typeof ApiDesignerClaimVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/claim-carousel': {
      id: '/api/designer/claim-carousel'
      path: '/api/designer/claim-carousel'
      fullPath: '/api/designer/claim-carousel'
      preLoaderRoute: typeof ApiDesignerClaimCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/claim': {
      id: '/api/designer/claim'
      path: '/api/designer/claim'
      fullPath: '/api/designer/claim'
      preLoaderRoute: typeof ApiDesignerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/carousel-requests': {
      id: '/api/designer/carousel-requests'
      path: '/api/designer/carousel-requests'
      fullPath: '/api/designer/carousel-requests'
      preLoaderRoute: typeof ApiDesignerCarouselRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify-pin': {
      id: '/api/admin/verify-pin'
      path: '/api/admin/verify-pin'
      fullPath: '/api/admin/verify-pin'
      preLoaderRoute: typeof ApiAdminVerifyPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-request': {
      id: '/api/admin/update-request'
      path: '/api/admin/update-request'
      fullPath: '/api/admin/update-request'
      preLoaderRoute: typeof ApiAdminUpdateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-discount-code': {
      id: '/api/admin/update-discount-code'
      path: '/api/admin/update-discount-code'
      fullPath: '/api/admin/update-discount-code'
      preLoaderRoute: typeof ApiAdminUpdateDiscountCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-designer': {
      id: '/api/admin/update-designer'
      path: '/api/admin/update-designer'
      fullPath: '/api/admin/update-designer'
      preLoaderRoute: typeof ApiAdminUpdateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-brand-profile': {
      id: '/api/admin/update-brand-profile'
      path: '/api/admin/update-brand-profile'
      fullPath: '/api/admin/update-brand-profile'
      preLoaderRoute: typeof ApiAdminUpdateBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/toggle-logo-visibility': {
      id: '/api/admin/toggle-logo-visibility'
      path: '/api/admin/toggle-logo-visibility'
      fullPath: '/api/admin/toggle-logo-visibility'
      preLoaderRoute: typeof ApiAdminToggleLogoVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/grant-requests': {
      id: '/api/admin/grant-requests'
      path: '/api/admin/grant-requests'
      fullPath: '/api/admin/grant-requests'
      preLoaderRoute: typeof ApiAdminGrantRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/discard-result': {
      id: '/api/admin/discard-result'
      path: '/api/admin/discard-result'
      fullPath: '/api/admin/discard-result'
      preLoaderRoute: typeof ApiAdminDiscardResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliver-video': {
      id: '/api/admin/deliver-video'
      path: '/api/admin/deliver-video'
      fullPath: '/api/admin/deliver-video'
      preLoaderRoute: typeof ApiAdminDeliverVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliver-carousel-slide': {
      id: '/api/admin/deliver-carousel-slide'
      path: '/api/admin/deliver-carousel-slide'
      fullPath: '/api/admin/deliver-carousel-slide'
      preLoaderRoute: typeof ApiAdminDeliverCarouselSlideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliver': {
      id: '/api/admin/deliver'
      path: '/api/admin/deliver'
      fullPath: '/api/admin/deliver'
      preLoaderRoute: typeof ApiAdminDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-request': {
      id: '/api/admin/delete-request'
      path: '/api/admin/delete-request'
      fullPath: '/api/admin/delete-request'
      preLoaderRoute: typeof ApiAdminDeleteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-discount-code': {
      id: '/api/admin/delete-discount-code'
      path: '/api/admin/delete-discount-code'
      fullPath: '/api/admin/delete-discount-code'
      preLoaderRoute: typeof ApiAdminDeleteDiscountCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deactivate-discount-code': {
      id: '/api/admin/deactivate-discount-code'
      path: '/api/admin/deactivate-discount-code'
      fullPath: '/api/admin/deactivate-discount-code'
      preLoaderRoute: typeof ApiAdminDeactivateDiscountCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deactivate-designer': {
      id: '/api/admin/deactivate-designer'
      path: '/api/admin/deactivate-designer'
      fullPath: '/api/admin/deactivate-designer'
      preLoaderRoute: typeof ApiAdminDeactivateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-discount-code': {
      id: '/api/admin/create-discount-code'
      path: '/api/admin/create-discount-code'
      fullPath: '/api/admin/create-discount-code'
      preLoaderRoute: typeof ApiAdminCreateDiscountCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-designer': {
      id: '/api/admin/create-designer'
      path: '/api/admin/create-designer'
      fullPath: '/api/admin/create-designer'
      preLoaderRoute: typeof ApiAdminCreateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-result': {
      id: '/api/admin/approve-result'
      path: '/api/admin/approve-result'
      fullPath: '/api/admin/approve-result'
      preLoaderRoute: typeof ApiAdminApproveResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai-fill': {
      id: '/api/admin/ai-fill'
      path: '/api/admin/ai-fill'
      fullPath: '/api/admin/ai-fill'
      preLoaderRoute: typeof ApiAdminAiFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activate-membership': {
      id: '/api/admin/activate-membership'
      path: '/api/admin/activate-membership'
      fullPath: '/api/admin/activate-membership'
      preLoaderRoute: typeof ApiAdminActivateMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activate-change': {
      id: '/api/admin/activate-change'
      path: '/api/admin/activate-change'
      fullPath: '/api/admin/activate-change'
      preLoaderRoute: typeof ApiAdminActivateChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/update-name': {
      id: '/api/account/update-name'
      path: '/api/account/update-name'
      fullPath: '/api/account/update-name'
      preLoaderRoute: typeof ApiAccountUpdateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/change-password': {
      id: '/api/account/change-password'
      path: '/api/account/change-password'
      fullPath: '/api/account/change-password'
      preLoaderRoute: typeof ApiAccountChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLabRoute: AdminLabRoute,
  CheckoutRoute: CheckoutRoute,
  IngresarRoute: IngresarRoute,
  MarcaRoute: MarcaRoute,
  NuestraHistoriaRoute: NuestraHistoriaRoute,
  PanelRoute: PanelRoute,
  PautaRoute: PautaRoute,
  RegistroRoute: RegistroRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  UpgradeRoute: UpgradeRoute,
  WiterRoute: WiterRoute,
  ApiBrandProfileRoute: ApiBrandProfileRoute,
  ApiBrandProfileColorsRoute: ApiBrandProfileColorsRoute,
  ApiBrandProfileManualRoute: ApiBrandProfileManualRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiCampaignsCreateRoute: ApiCampaignsCreateRoute,
  ApiCarouselRequestChangeRoute: ApiCarouselRequestChangeRoute,
  ApiCarouselRequestsRoute: ApiCarouselRequestsRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCloseRequestRoute: ApiCloseRequestRoute,
  ApiFileRoute: ApiFileRoute,
  ApiGenerateAdCopyRoute: ApiGenerateAdCopyRoute,
  ApiGeoPriceRoute: ApiGeoPriceRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiMetaInterestSearchRoute: ApiMetaInterestSearchRoute,
  ApiMetaInterestSuggestionsRoute: ApiMetaInterestSuggestionsRoute,
  ApiMetaLocationSearchRoute: ApiMetaLocationSearchRoute,
  ApiPurchasePackRoute: ApiPurchasePackRoute,
  ApiRequestChangeRoute: ApiRequestChangeRoute,
  ApiRequestRevisionRoute: ApiRequestRevisionRoute,
  ApiRequestsRoute: ApiRequestsRoute,
  ApiSubmitSatisfactionRoute: ApiSubmitSatisfactionRoute,
  ApiUploadReferenceRoute: ApiUploadReferenceRoute,
  ApiUploadVideoRawRoute: ApiUploadVideoRawRoute,
  ApiUserRoute: ApiUserRoute,
  ApiVideoRequestsRoute: ApiVideoRequestsRoute,
  ApiWitVideoIdeaRoute: ApiWitVideoIdeaRoute,
  ApiAccountChangePasswordRoute: ApiAccountChangePasswordRoute,
  ApiAccountUpdateNameRoute: ApiAccountUpdateNameRoute,
  ApiAdminActivateChangeRoute: ApiAdminActivateChangeRoute,
  ApiAdminActivateMembershipRoute: ApiAdminActivateMembershipRoute,
  ApiAdminAiFillRoute: ApiAdminAiFillRoute,
  ApiAdminApproveResultRoute: ApiAdminApproveResultRoute,
  ApiAdminCreateDesignerRoute: ApiAdminCreateDesignerRoute,
  ApiAdminCreateDiscountCodeRoute: ApiAdminCreateDiscountCodeRoute,
  ApiAdminDeactivateDesignerRoute: ApiAdminDeactivateDesignerRoute,
  ApiAdminDeactivateDiscountCodeRoute: ApiAdminDeactivateDiscountCodeRoute,
  ApiAdminDeleteDiscountCodeRoute: ApiAdminDeleteDiscountCodeRoute,
  ApiAdminDeleteRequestRoute: ApiAdminDeleteRequestRoute,
  ApiAdminDeliverRoute: ApiAdminDeliverRoute,
  ApiAdminDeliverCarouselSlideRoute: ApiAdminDeliverCarouselSlideRoute,
  ApiAdminDeliverVideoRoute: ApiAdminDeliverVideoRoute,
  ApiAdminDiscardResultRoute: ApiAdminDiscardResultRoute,
  ApiAdminGrantRequestsRoute: ApiAdminGrantRequestsRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminToggleLogoVisibilityRoute: ApiAdminToggleLogoVisibilityRoute,
  ApiAdminUpdateBrandProfileRoute: ApiAdminUpdateBrandProfileRoute,
  ApiAdminUpdateDesignerRoute: ApiAdminUpdateDesignerRoute,
  ApiAdminUpdateDiscountCodeRoute: ApiAdminUpdateDiscountCodeRoute,
  ApiAdminUpdateRequestRoute: ApiAdminUpdateRequestRoute,
  ApiAdminVerifyPinRoute: ApiAdminVerifyPinRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDesignerCarouselRequestsRoute: ApiDesignerCarouselRequestsRoute,
  ApiDesignerClaimRoute: ApiDesignerClaimRoute,
  ApiDesignerClaimCarouselRoute: ApiDesignerClaimCarouselRoute,
  ApiDesignerClaimVideoRoute: ApiDesignerClaimVideoRoute,
  ApiDesignerRequestsRoute: ApiDesignerRequestsRoute,
  ApiDesignerVideoRequestsRoute: ApiDesignerVideoRequestsRoute,
  ApiOnboardingCompleteRoute: ApiOnboardingCompleteRoute,
  ApiOnboardingDraftRoute: ApiOnboardingDraftRoute,
  ApiPublicBrandLogoRoute: ApiPublicBrandLogoRoute,
  ApiPublicBrandsRoute: ApiPublicBrandsRoute,
  ApiPublicReviewsRoute: ApiPublicReviewsRoute,
  ApiPublicShowcaseRoute: ApiPublicShowcaseRoute,
  ApiPublicShowcaseImageRoute: ApiPublicShowcaseImageRoute,
  ApiStripeCreatePaymentIntentRoute: ApiStripeCreatePaymentIntentRoute,
  ApiWitCarouselChatRoute: ApiWitCarouselChatRoute,
  ApiWitChatRoute: ApiWitChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
