/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WiterRouteImport } from './routes/witer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as NuestraHistoriaRouteImport } from './routes/nuestra-historia'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminLabRouteImport } from './routes/admin-lab'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiUploadReferenceRouteImport } from './routes/api/upload-reference'
import { Route as ApiSubmitSatisfactionRouteImport } from './routes/api/submit-satisfaction'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiRequestRevisionRouteImport } from './routes/api/request-revision'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiCloseRequestRouteImport } from './routes/api/close-request'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiBrandProfileRouteImport } from './routes/api/brand-profile'
import { Route as ApiWitChatRouteImport } from './routes/api/wit/chat'
import { Route as ApiPublicShowcaseImageRouteImport } from './routes/api/public/showcase-image'
import { Route as ApiPublicShowcaseRouteImport } from './routes/api/public/showcase'
import { Route as ApiPublicReviewsRouteImport } from './routes/api/public/reviews'
import { Route as ApiPublicBrandsRouteImport } from './routes/api/public/brands'
import { Route as ApiPublicBrandLogoRouteImport } from './routes/api/public/brand-logo'
import { Route as ApiOnboardingDraftRouteImport } from './routes/api/onboarding/draft'
import { Route as ApiOnboardingCompleteRouteImport } from './routes/api/onboarding/complete'
import { Route as ApiDesignerRequestsRouteImport } from './routes/api/designer/requests'
import { Route as ApiDesignerClaimRouteImport } from './routes/api/designer/claim'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUpdateRequestRouteImport } from './routes/api/admin/update-request'
import { Route as ApiAdminUpdateDesignerRouteImport } from './routes/api/admin/update-designer'
import { Route as ApiAdminUpdateBrandProfileRouteImport } from './routes/api/admin/update-brand-profile'
import { Route as ApiAdminToggleLogoVisibilityRouteImport } from './routes/api/admin/toggle-logo-visibility'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminDiscardResultRouteImport } from './routes/api/admin/discard-result'
import { Route as ApiAdminDeliverRouteImport } from './routes/api/admin/deliver'
import { Route as ApiAdminDeleteRequestRouteImport } from './routes/api/admin/delete-request'
import { Route as ApiAdminDeactivateDesignerRouteImport } from './routes/api/admin/deactivate-designer'
import { Route as ApiAdminCreateDesignerRouteImport } from './routes/api/admin/create-designer'
import { Route as ApiAdminApproveResultRouteImport } from './routes/api/admin/approve-result'
import { Route as ApiAdminAiFillRouteImport } from './routes/api/admin/ai-fill'
import { Route as ApiAdminActivateMembershipRouteImport } from './routes/api/admin/activate-membership'

const WiterRoute = WiterRouteImport.update({
  id: '/witer',
  path: '/witer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const NuestraHistoriaRoute = NuestraHistoriaRouteImport.update({
  id: '/nuestra-historia',
  path: '/nuestra-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLabRoute = AdminLabRouteImport.update({
  id: '/admin-lab',
  path: '/admin-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadReferenceRoute = ApiUploadReferenceRouteImport.update({
  id: '/api/upload-reference',
  path: '/api/upload-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmitSatisfactionRoute = ApiSubmitSatisfactionRouteImport.update({
  id: '/api/submit-satisfaction',
  path: '/api/submit-satisfaction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestRevisionRoute = ApiRequestRevisionRouteImport.update({
  id: '/api/request-revision',
  path: '/api/request-revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloseRequestRoute = ApiCloseRequestRouteImport.update({
  id: '/api/close-request',
  path: '/api/close-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileRoute = ApiBrandProfileRouteImport.update({
  id: '/api/brand-profile',
  path: '/api/brand-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWitChatRoute = ApiWitChatRouteImport.update({
  id: '/api/wit/chat',
  path: '/api/wit/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShowcaseImageRoute = ApiPublicShowcaseImageRouteImport.update({
  id: '/api/public/showcase-image',
  path: '/api/public/showcase-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShowcaseRoute = ApiPublicShowcaseRouteImport.update({
  id: '/api/public/showcase',
  path: '/api/public/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReviewsRoute = ApiPublicReviewsRouteImport.update({
  id: '/api/public/reviews',
  path: '/api/public/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandsRoute = ApiPublicBrandsRouteImport.update({
  id: '/api/public/brands',
  path: '/api/public/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBrandLogoRoute = ApiPublicBrandLogoRouteImport.update({
  id: '/api/public/brand-logo',
  path: '/api/public/brand-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingDraftRoute = ApiOnboardingDraftRouteImport.update({
  id: '/api/onboarding/draft',
  path: '/api/onboarding/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCompleteRoute = ApiOnboardingCompleteRouteImport.update({
  id: '/api/onboarding/complete',
  path: '/api/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerRequestsRoute = ApiDesignerRequestsRouteImport.update({
  id: '/api/designer/requests',
  path: '/api/designer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignerClaimRoute = ApiDesignerClaimRouteImport.update({
  id: '/api/designer/claim',
  path: '/api/designer/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateRequestRoute = ApiAdminUpdateRequestRouteImport.update({
  id: '/api/admin/update-request',
  path: '/api/admin/update-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateDesignerRoute = ApiAdminUpdateDesignerRouteImport.update({
  id: '/api/admin/update-designer',
  path: '/api/admin/update-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateBrandProfileRoute =
  ApiAdminUpdateBrandProfileRouteImport.update({
    id: '/api/admin/update-brand-profile',
    path: '/api/admin/update-brand-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminToggleLogoVisibilityRoute =
  ApiAdminToggleLogoVisibilityRouteImport.update({
    id: '/api/admin/toggle-logo-visibility',
    path: '/api/admin/toggle-logo-visibility',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDiscardResultRoute = ApiAdminDiscardResultRouteImport.update({
  id: '/api/admin/discard-result',
  path: '/api/admin/discard-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliverRoute = ApiAdminDeliverRouteImport.update({
  id: '/api/admin/deliver',
  path: '/api/admin/deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeleteRequestRoute = ApiAdminDeleteRequestRouteImport.update({
  id: '/api/admin/delete-request',
  path: '/api/admin/delete-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeactivateDesignerRoute =
  ApiAdminDeactivateDesignerRouteImport.update({
    id: '/api/admin/deactivate-designer',
    path: '/api/admin/deactivate-designer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCreateDesignerRoute = ApiAdminCreateDesignerRouteImport.update({
  id: '/api/admin/create-designer',
  path: '/api/admin/create-designer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApproveResultRoute = ApiAdminApproveResultRouteImport.update({
  id: '/api/admin/approve-result',
  path: '/api/admin/approve-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAiFillRoute = ApiAdminAiFillRouteImport.update({
  id: '/api/admin/ai-fill',
  path: '/api/admin/ai-fill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivateMembershipRoute =
  ApiAdminActivateMembershipRouteImport.update({
    id: '/api/admin/activate-membership',
    path: '/api/admin/activate-membership',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-lab': typeof AdminLabRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/nuestra-historia': typeof NuestraHistoriaRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/witer': typeof WiterRoute
  '/api/brand-profile': typeof ApiBrandProfileRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/close-request': typeof ApiCloseRequestRoute
  '/api/file': typeof ApiFileRoute
  '/api/request-revision': typeof ApiRequestRevisionRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/submit-satisfaction': typeof ApiSubmitSatisfactionRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/activate-membership': typeof ApiAdminActivateMembershipRoute
  '/api/admin/ai-fill': typeof ApiAdminAiFillRoute
  '/api/admin/approve-result': typeof ApiAdminApproveResultRoute
  '/api/admin/create-designer': typeof ApiAdminCreateDesignerRoute
  '/api/admin/deactivate-designer': typeof ApiAdminDeactivateDesignerRoute
  '/api/admin/delete-request': typeof ApiAdminDeleteRequestRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/discard-result': typeof ApiAdminDiscardResultRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/toggle-logo-visibility': typeof ApiAdminToggleLogoVisibilityRoute
  '/api/admin/update-brand-profile': typeof ApiAdminUpdateBrandProfileRoute
  '/api/admin/update-designer': typeof ApiAdminUpdateDesignerRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/designer/claim': typeof ApiDesignerClaimRoute
  '/api/designer/requests': typeof ApiDesignerRequestsRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/draft': typeof ApiOnboardingDraftRoute
  '/api/public/brand-logo': typeof ApiPublicBrandLogoRoute
  '/api/public/brands': typeof ApiPublicBrandsRoute
  '/api/public/reviews': typeof ApiPublicReviewsRoute
  '/api/public/showcase': typeof ApiPublicShowcaseRoute
  '/api/public/showcase-image': typeof ApiPublicShowcaseImageRoute
  '/api/wit/chat': typeof ApiWitChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/nuestra-historia'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/witer'
    | '/api/brand-profile'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/deactivate-designer'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/discard-result'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/claim'
    | '/api/designer/requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/wit/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/nuestra-historia'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/witer'
    | '/api/brand-profile'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/deactivate-designer'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/discard-result'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/claim'
    | '/api/designer/requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/wit/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-lab'
    | '/checkout'
    | '/ingresar'
    | '/nuestra-historia'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/witer'
    | '/api/brand-profile'
    | '/api/checkout'
    | '/api/close-request'
    | '/api/file'
    | '/api/request-revision'
    | '/api/requests'
    | '/api/submit-satisfaction'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/activate-membership'
    | '/api/admin/ai-fill'
    | '/api/admin/approve-result'
    | '/api/admin/create-designer'
    | '/api/admin/deactivate-designer'
    | '/api/admin/delete-request'
    | '/api/admin/deliver'
    | '/api/admin/discard-result'
    | '/api/admin/overview'
    | '/api/admin/toggle-logo-visibility'
    | '/api/admin/update-brand-profile'
    | '/api/admin/update-designer'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/designer/claim'
    | '/api/designer/requests'
    | '/api/onboarding/complete'
    | '/api/onboarding/draft'
    | '/api/public/brand-logo'
    | '/api/public/brands'
    | '/api/public/reviews'
    | '/api/public/showcase'
    | '/api/public/showcase-image'
    | '/api/wit/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLabRoute: typeof AdminLabRoute
  CheckoutRoute: typeof CheckoutRoute
  IngresarRoute: typeof IngresarRoute
  NuestraHistoriaRoute: typeof NuestraHistoriaRoute
  PanelRoute: typeof PanelRoute
  RegistroRoute: typeof RegistroRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WiterRoute: typeof WiterRoute
  ApiBrandProfileRoute: typeof ApiBrandProfileRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCloseRequestRoute: typeof ApiCloseRequestRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiRequestRevisionRoute: typeof ApiRequestRevisionRoute
  ApiRequestsRoute: typeof ApiRequestsRoute
  ApiSubmitSatisfactionRoute: typeof ApiSubmitSatisfactionRoute
  ApiUploadReferenceRoute: typeof ApiUploadReferenceRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiAdminActivateMembershipRoute: typeof ApiAdminActivateMembershipRoute
  ApiAdminAiFillRoute: typeof ApiAdminAiFillRoute
  ApiAdminApproveResultRoute: typeof ApiAdminApproveResultRoute
  ApiAdminCreateDesignerRoute: typeof ApiAdminCreateDesignerRoute
  ApiAdminDeactivateDesignerRoute: typeof ApiAdminDeactivateDesignerRoute
  ApiAdminDeleteRequestRoute: typeof ApiAdminDeleteRequestRoute
  ApiAdminDeliverRoute: typeof ApiAdminDeliverRoute
  ApiAdminDiscardResultRoute: typeof ApiAdminDiscardResultRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminToggleLogoVisibilityRoute: typeof ApiAdminToggleLogoVisibilityRoute
  ApiAdminUpdateBrandProfileRoute: typeof ApiAdminUpdateBrandProfileRoute
  ApiAdminUpdateDesignerRoute: typeof ApiAdminUpdateDesignerRoute
  ApiAdminUpdateRequestRoute: typeof ApiAdminUpdateRequestRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDesignerClaimRoute: typeof ApiDesignerClaimRoute
  ApiDesignerRequestsRoute: typeof ApiDesignerRequestsRoute
  ApiOnboardingCompleteRoute: typeof ApiOnboardingCompleteRoute
  ApiOnboardingDraftRoute: typeof ApiOnboardingDraftRoute
  ApiPublicBrandLogoRoute: typeof ApiPublicBrandLogoRoute
  ApiPublicBrandsRoute: typeof ApiPublicBrandsRoute
  ApiPublicReviewsRoute: typeof ApiPublicReviewsRoute
  ApiPublicShowcaseRoute: typeof ApiPublicShowcaseRoute
  ApiPublicShowcaseImageRoute: typeof ApiPublicShowcaseImageRoute
  ApiWitChatRoute: typeof ApiWitChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/witer': {
      id: '/witer'
      path: '/witer'
      fullPath: '/witer'
      preLoaderRoute: typeof WiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuestra-historia': {
      id: '/nuestra-historia'
      path: '/nuestra-historia'
      fullPath: '/nuestra-historia'
      preLoaderRoute: typeof NuestraHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-lab': {
      id: '/admin-lab'
      path: '/admin-lab'
      fullPath: '/admin-lab'
      preLoaderRoute: typeof AdminLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-reference': {
      id: '/api/upload-reference'
      path: '/api/upload-reference'
      fullPath: '/api/upload-reference'
      preLoaderRoute: typeof ApiUploadReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submit-satisfaction': {
      id: '/api/submit-satisfaction'
      path: '/api/submit-satisfaction'
      fullPath: '/api/submit-satisfaction'
      preLoaderRoute: typeof ApiSubmitSatisfactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-revision': {
      id: '/api/request-revision'
      path: '/api/request-revision'
      fullPath: '/api/request-revision'
      preLoaderRoute: typeof ApiRequestRevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/close-request': {
      id: '/api/close-request'
      path: '/api/close-request'
      fullPath: '/api/close-request'
      preLoaderRoute: typeof ApiCloseRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-profile': {
      id: '/api/brand-profile'
      path: '/api/brand-profile'
      fullPath: '/api/brand-profile'
      preLoaderRoute: typeof ApiBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wit/chat': {
      id: '/api/wit/chat'
      path: '/api/wit/chat'
      fullPath: '/api/wit/chat'
      preLoaderRoute: typeof ApiWitChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/showcase-image': {
      id: '/api/public/showcase-image'
      path: '/api/public/showcase-image'
      fullPath: '/api/public/showcase-image'
      preLoaderRoute: typeof ApiPublicShowcaseImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/showcase': {
      id: '/api/public/showcase'
      path: '/api/public/showcase'
      fullPath: '/api/public/showcase'
      preLoaderRoute: typeof ApiPublicShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reviews': {
      id: '/api/public/reviews'
      path: '/api/public/reviews'
      fullPath: '/api/public/reviews'
      preLoaderRoute: typeof ApiPublicReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brands': {
      id: '/api/public/brands'
      path: '/api/public/brands'
      fullPath: '/api/public/brands'
      preLoaderRoute: typeof ApiPublicBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/brand-logo': {
      id: '/api/public/brand-logo'
      path: '/api/public/brand-logo'
      fullPath: '/api/public/brand-logo'
      preLoaderRoute: typeof ApiPublicBrandLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/draft': {
      id: '/api/onboarding/draft'
      path: '/api/onboarding/draft'
      fullPath: '/api/onboarding/draft'
      preLoaderRoute: typeof ApiOnboardingDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/complete': {
      id: '/api/onboarding/complete'
      path: '/api/onboarding/complete'
      fullPath: '/api/onboarding/complete'
      preLoaderRoute: typeof ApiOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/requests': {
      id: '/api/designer/requests'
      path: '/api/designer/requests'
      fullPath: '/api/designer/requests'
      preLoaderRoute: typeof ApiDesignerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/designer/claim': {
      id: '/api/designer/claim'
      path: '/api/designer/claim'
      fullPath: '/api/designer/claim'
      preLoaderRoute: typeof ApiDesignerClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-request': {
      id: '/api/admin/update-request'
      path: '/api/admin/update-request'
      fullPath: '/api/admin/update-request'
      preLoaderRoute: typeof ApiAdminUpdateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-designer': {
      id: '/api/admin/update-designer'
      path: '/api/admin/update-designer'
      fullPath: '/api/admin/update-designer'
      preLoaderRoute: typeof ApiAdminUpdateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-brand-profile': {
      id: '/api/admin/update-brand-profile'
      path: '/api/admin/update-brand-profile'
      fullPath: '/api/admin/update-brand-profile'
      preLoaderRoute: typeof ApiAdminUpdateBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/toggle-logo-visibility': {
      id: '/api/admin/toggle-logo-visibility'
      path: '/api/admin/toggle-logo-visibility'
      fullPath: '/api/admin/toggle-logo-visibility'
      preLoaderRoute: typeof ApiAdminToggleLogoVisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/discard-result': {
      id: '/api/admin/discard-result'
      path: '/api/admin/discard-result'
      fullPath: '/api/admin/discard-result'
      preLoaderRoute: typeof ApiAdminDiscardResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliver': {
      id: '/api/admin/deliver'
      path: '/api/admin/deliver'
      fullPath: '/api/admin/deliver'
      preLoaderRoute: typeof ApiAdminDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/delete-request': {
      id: '/api/admin/delete-request'
      path: '/api/admin/delete-request'
      fullPath: '/api/admin/delete-request'
      preLoaderRoute: typeof ApiAdminDeleteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deactivate-designer': {
      id: '/api/admin/deactivate-designer'
      path: '/api/admin/deactivate-designer'
      fullPath: '/api/admin/deactivate-designer'
      preLoaderRoute: typeof ApiAdminDeactivateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/create-designer': {
      id: '/api/admin/create-designer'
      path: '/api/admin/create-designer'
      fullPath: '/api/admin/create-designer'
      preLoaderRoute: typeof ApiAdminCreateDesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approve-result': {
      id: '/api/admin/approve-result'
      path: '/api/admin/approve-result'
      fullPath: '/api/admin/approve-result'
      preLoaderRoute: typeof ApiAdminApproveResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ai-fill': {
      id: '/api/admin/ai-fill'
      path: '/api/admin/ai-fill'
      fullPath: '/api/admin/ai-fill'
      preLoaderRoute: typeof ApiAdminAiFillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activate-membership': {
      id: '/api/admin/activate-membership'
      path: '/api/admin/activate-membership'
      fullPath: '/api/admin/activate-membership'
      preLoaderRoute: typeof ApiAdminActivateMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLabRoute: AdminLabRoute,
  CheckoutRoute: CheckoutRoute,
  IngresarRoute: IngresarRoute,
  NuestraHistoriaRoute: NuestraHistoriaRoute,
  PanelRoute: PanelRoute,
  RegistroRoute: RegistroRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WiterRoute: WiterRoute,
  ApiBrandProfileRoute: ApiBrandProfileRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCloseRequestRoute: ApiCloseRequestRoute,
  ApiFileRoute: ApiFileRoute,
  ApiRequestRevisionRoute: ApiRequestRevisionRoute,
  ApiRequestsRoute: ApiRequestsRoute,
  ApiSubmitSatisfactionRoute: ApiSubmitSatisfactionRoute,
  ApiUploadReferenceRoute: ApiUploadReferenceRoute,
  ApiUserRoute: ApiUserRoute,
  ApiAdminActivateMembershipRoute: ApiAdminActivateMembershipRoute,
  ApiAdminAiFillRoute: ApiAdminAiFillRoute,
  ApiAdminApproveResultRoute: ApiAdminApproveResultRoute,
  ApiAdminCreateDesignerRoute: ApiAdminCreateDesignerRoute,
  ApiAdminDeactivateDesignerRoute: ApiAdminDeactivateDesignerRoute,
  ApiAdminDeleteRequestRoute: ApiAdminDeleteRequestRoute,
  ApiAdminDeliverRoute: ApiAdminDeliverRoute,
  ApiAdminDiscardResultRoute: ApiAdminDiscardResultRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminToggleLogoVisibilityRoute: ApiAdminToggleLogoVisibilityRoute,
  ApiAdminUpdateBrandProfileRoute: ApiAdminUpdateBrandProfileRoute,
  ApiAdminUpdateDesignerRoute: ApiAdminUpdateDesignerRoute,
  ApiAdminUpdateRequestRoute: ApiAdminUpdateRequestRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDesignerClaimRoute: ApiDesignerClaimRoute,
  ApiDesignerRequestsRoute: ApiDesignerRequestsRoute,
  ApiOnboardingCompleteRoute: ApiOnboardingCompleteRoute,
  ApiOnboardingDraftRoute: ApiOnboardingDraftRoute,
  ApiPublicBrandLogoRoute: ApiPublicBrandLogoRoute,
  ApiPublicBrandsRoute: ApiPublicBrandsRoute,
  ApiPublicReviewsRoute: ApiPublicReviewsRoute,
  ApiPublicShowcaseRoute: ApiPublicShowcaseRoute,
  ApiPublicShowcaseImageRoute: ApiPublicShowcaseImageRoute,
  ApiWitChatRoute: ApiWitChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
