/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRouteImport } from './routes/api/user'
import { Route as ApiUploadReferenceRouteImport } from './routes/api/upload-reference'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiFileRouteImport } from './routes/api/file'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiAiAutofillRouteImport } from './routes/api/ai-autofill'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUpdateRequestRouteImport } from './routes/api/admin/update-request'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAdminGenerateRouteImport } from './routes/api/admin/generate'
import { Route as ApiAdminDeliverRouteImport } from './routes/api/admin/deliver'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRoute = ApiUserRouteImport.update({
  id: '/api/user',
  path: '/api/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadReferenceRoute = ApiUploadReferenceRouteImport.update({
  id: '/api/upload-reference',
  path: '/api/upload-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFileRoute = ApiFileRouteImport.update({
  id: '/api/file',
  path: '/api/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAutofillRoute = ApiAiAutofillRouteImport.update({
  id: '/api/ai-autofill',
  path: '/api/ai-autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdateRequestRoute = ApiAdminUpdateRequestRouteImport.update({
  id: '/api/admin/update-request',
  path: '/api/admin/update-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGenerateRoute = ApiAdminGenerateRouteImport.update({
  id: '/api/admin/generate',
  path: '/api/admin/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeliverRoute = ApiAdminDeliverRouteImport.update({
  id: '/api/admin/deliver',
  path: '/api/admin/deliver',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-autofill': typeof ApiAiAutofillRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/file': typeof ApiFileRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-autofill': typeof ApiAiAutofillRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/file': typeof ApiFileRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/registro': typeof RegistroRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/ai-autofill': typeof ApiAiAutofillRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/file': typeof ApiFileRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/upload-reference': typeof ApiUploadReferenceRoute
  '/api/user': typeof ApiUserRoute
  '/api/admin/deliver': typeof ApiAdminDeliverRoute
  '/api/admin/generate': typeof ApiAdminGenerateRoute
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/admin/update-request': typeof ApiAdminUpdateRequestRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/ingresar'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/ai-autofill'
    | '/api/checkout'
    | '/api/file'
    | '/api/requests'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/deliver'
    | '/api/admin/generate'
    | '/api/admin/overview'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/ingresar'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/ai-autofill'
    | '/api/checkout'
    | '/api/file'
    | '/api/requests'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/deliver'
    | '/api/admin/generate'
    | '/api/admin/overview'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/ingresar'
    | '/panel'
    | '/registro'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/ai-autofill'
    | '/api/checkout'
    | '/api/file'
    | '/api/requests'
    | '/api/upload-reference'
    | '/api/user'
    | '/api/admin/deliver'
    | '/api/admin/generate'
    | '/api/admin/overview'
    | '/api/admin/update-request'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  IngresarRoute: typeof IngresarRoute
  PanelRoute: typeof PanelRoute
  RegistroRoute: typeof RegistroRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAiAutofillRoute: typeof ApiAiAutofillRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiFileRoute: typeof ApiFileRoute
  ApiRequestsRoute: typeof ApiRequestsRoute
  ApiUploadReferenceRoute: typeof ApiUploadReferenceRoute
  ApiUserRoute: typeof ApiUserRoute
  ApiAdminDeliverRoute: typeof ApiAdminDeliverRoute
  ApiAdminGenerateRoute: typeof ApiAdminGenerateRoute
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAdminUpdateRequestRoute: typeof ApiAdminUpdateRequestRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user': {
      id: '/api/user'
      path: '/api/user'
      fullPath: '/api/user'
      preLoaderRoute: typeof ApiUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-reference': {
      id: '/api/upload-reference'
      path: '/api/upload-reference'
      fullPath: '/api/upload-reference'
      preLoaderRoute: typeof ApiUploadReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/file': {
      id: '/api/file'
      path: '/api/file'
      fullPath: '/api/file'
      preLoaderRoute: typeof ApiFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-autofill': {
      id: '/api/ai-autofill'
      path: '/api/ai-autofill'
      fullPath: '/api/ai-autofill'
      preLoaderRoute: typeof ApiAiAutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-request': {
      id: '/api/admin/update-request'
      path: '/api/admin/update-request'
      fullPath: '/api/admin/update-request'
      preLoaderRoute: typeof ApiAdminUpdateRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/generate': {
      id: '/api/admin/generate'
      path: '/api/admin/generate'
      fullPath: '/api/admin/generate'
      preLoaderRoute: typeof ApiAdminGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deliver': {
      id: '/api/admin/deliver'
      path: '/api/admin/deliver'
      fullPath: '/api/admin/deliver'
      preLoaderRoute: typeof ApiAdminDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  IngresarRoute: IngresarRoute,
  PanelRoute: PanelRoute,
  RegistroRoute: RegistroRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAiAutofillRoute: ApiAiAutofillRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiFileRoute: ApiFileRoute,
  ApiRequestsRoute: ApiRequestsRoute,
  ApiUploadReferenceRoute: ApiUploadReferenceRoute,
  ApiUserRoute: ApiUserRoute,
  ApiAdminDeliverRoute: ApiAdminDeliverRoute,
  ApiAdminGenerateRoute: ApiAdminGenerateRoute,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAdminUpdateRequestRoute: ApiAdminUpdateRequestRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
